[package]
name = "pangocairo"
documentation = "https://gtk-rs.org/gtk-rs-core/stable/latest/docs/pangocairo/"
homepage = "https://gtk-rs.org/"
authors = ["The gtk-rs Project Developers"]
keywords = ["pango", "cairo", "gtk-rs", "gnome"]
readme = "README.md"
version = "0.14.8"
description = "Rust bindings for the PangoCairo library"
repository = "https://github.com/gtk-rs/gtk-rs-core"
license = "MIT"
exclude = [
    "gir-files/*",
]
edition = "2018"

[features]
dox = ["glib/dox", "pango/dox", "cairo-rs/dox"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
libc = "0.2"
bitflags = "1.0"
ffi = {package = "pangocairo-sys", path = "./sys", version = "0.14.0"}
glib = {version = "0.14.0", path = "./../glib"}
pango = {version ="0.14.0", path = "./../pango"}
cairo-rs = {version= "0.14.0", path = "./../cairo"}

[dev-dependencies]
gir-format-check = "^0.1"
