name: github packages

on:
  push:
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          push: true
          allow: security.insecure
          tags: ${{ github.repository }}/core:latest
